---
title: "Bertrand's Paradox"
author: "Shelby Tisdale"
format: html
---

```{r}
#| label: load-packages
library(tidyverse)
library(latex2exp)
library(ggforce)
library(gganimate)
library(extrafont)
loadfonts()
```


```{r}
#| warning: false

#create data frame
df <- data.frame(x=c(1, 2, 2, 3, 3, 4, 8),
                 y=c(2, 4, 5, 4, 7, 9, 10))

#create scatter plot with circle
ggplot(data = df, aes(x, y)) +
  annotate("segment", x = 0, y = 1, xend = -(3^(1/2))/2, yend = -0.5, color = "slateblue4", lwd = 1) +
  annotate("segment", x = 0, y = 1, xend = (3^(1/2))/2, yend = -0.5, color = "slateblue4", lwd = 1) +
  annotate("segment", x = -(3^(1/2))/2, y = -0.5, xend = (3^(1/2))/2, yend = -0.5, color = "slateblue4", lwd = 1) +
  geom_circle(aes(x0=0, y0=0, r=1), lwd=1, inherit.aes=FALSE) +
  annotate("segment", x = -1, y = 0, xend = 0, yend = 0, lwd = 1) +
  annotate("text", x  = -0.2, y = 0.1, label = "r = 1", size = 6) +
  annotate("text", x = 0.65, y = 0.2, label = TeX("$\\sqrt{3}$"), color = "slateblue4", size = 8, family = "CM Roman") +
  annotate("text", x = -0.65, y = 0.2, label = TeX("$\\sqrt{3}$"), color = "slateblue4", size = 8, family = "CM Roman") +
  annotate("text", x = 0, y = -0.65, label = TeX("$\\sqrt{3}$"), color = "slateblue4", size = 8, family = "CM Roman") +
  theme_void() +
  theme(text = element_text(family="CM Roman")) +
  coord_fixed() 
```
```{r}
ggplot(data = df, aes(x, y)) +
  annotate("segment", x = 0, y = 1, xend = -(3^(1/2))/2, yend = -0.5, color = "slateblue4", lwd = 1) +
  annotate("segment", x = 0, y = 1, xend = (3^(1/2))/2, yend = -0.5, color = "slateblue4", lwd = 1) +
  annotate("segment", x = -(3^(1/2))/2, y = -0.5, xend = (3^(1/2))/2, yend = -0.5, color = "slateblue4", lwd = 1) +
  geom_circle(aes(x0=0, y0=0, r=1), lwd=1, inherit.aes=FALSE) +
  annotate("segment", x = -1, y = 0, xend = 0, yend = 0, lwd = 1) +
  annotate("text", x  = -0.2, y = 0.1, label = "r = 1", size = 6) +
  annotate("text", x = 0.65, y = 0.2, label = TeX("$\\sqrt{3}$"), color = "slateblue4", size = 8) +
  annotate("text", x = -0.65, y = 0.2, label = TeX("$\\sqrt{3}$"), color = "slateblue4", size = 8) +
  annotate("text", x = 0, y = -0.65, label = TeX("$\\sqrt{3}$"), color = "slateblue4", size = 8) +
  theme_void() +
  coord_fixed() 
```

